// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Search() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"search\" class=\"flex flex-col gap-4\"><h1 class=\"text-2xl font-bold\">Hello and welcome to Pokemon search page!</h1><h2>Feel free to check types of pokemons or search a specific one.</h2><input type=\"text\" hx-trigger=\"change\" hx-put=\"/search\" placeholder=\"pikachu\" name=\"query\" class=\"shadow-xl bg-gray-300 rounded-md pl-2 py-1 mr-6\"><div id=\"search-buttons\"><button hx-get=\"/search/query\" hx-target=\"#content\" class=\"rounded-md bg-gray-300 px-4 shadow-md\">Search</button> <button hx-get=\"/search/random\" hx-target=\"#content\" class=\"rounded-md bg-gray-300 px-4 shadow-md\">I feel lucky!</button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
